/** EventForm — reusable event create/edit form. */
import { useState } from 'react';
import Input from '../common/Input';
import Button from '../common/Button';
import { EVENT_CATEGORIES } from '../../config/constants';
export default function EventForm({ initialData = {}, onSubmit, loading = false }) {
  const [form, setForm] = useState({ title: '', description: '', category: 'technical', date: '', time: '', venue: '', max_participants: 0, ...initialData });
  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const handleSubmit = (e) => { e.preventDefault(); onSubmit(form); };
  return (<form onSubmit={handleSubmit}><Input label="Event Title" name="title" value={form.title} onChange={handleChange} required /><div className="mb-4"><label className="block mb-1.5 text-sm font-medium" style={{ color: 'var(--color-text-primary)' }}>Description <span style={{ color: 'var(--color-danger)' }}>*</span></label><textarea name="description" value={form.description} onChange={handleChange} required rows={4} className="w-full rounded-lg p-3 text-sm" style={{ backgroundColor: 'var(--color-surface-secondary)', border: '1px solid var(--color-border)', color: 'var(--color-text-primary)', resize: 'vertical' }} /></div><div className="mb-4"><label className="block mb-1.5 text-sm font-medium" style={{ color: 'var(--color-text-primary)' }}>Category</label><select name="category" value={form.category} onChange={handleChange} className="w-full rounded-lg p-2.5 text-sm" style={{ backgroundColor: 'var(--color-surface-secondary)', border: '1px solid var(--color-border)', color: 'var(--color-text-primary)' }}>{EVENT_CATEGORIES.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}</select></div><div className="grid grid-cols-2 gap-4"><Input label="Date" name="date" type="datetime-local" value={form.date} onChange={handleChange} required /><Input label="Time" name="time" value={form.time} onChange={handleChange} placeholder="e.g. 10:00 AM - 1:00 PM" /></div><div className="grid grid-cols-2 gap-4"><Input label="Venue" name="venue" value={form.venue} onChange={handleChange} required /><Input label="Max Participants" name="max_participants" type="number" value={form.max_participants} onChange={handleChange} /></div><Button type="submit" loading={loading} fullWidth className="mt-2">{initialData.title ? 'Update Event' : 'Create Event'}</Button></form>);
}
