/** MemberForm — association member form. */
import { useState } from 'react';
import Input from '../common/Input';
import Button from '../common/Button';
import { MEMBER_ROLES, ACADEMIC_YEARS } from '../../config/constants';
export default function MemberForm({ initialData = {}, onSubmit, loading = false }) {
  const [form, setForm] = useState({ name: '', email: '', phone: '', role: 'member', department: '', year: 1, order: 0, ...initialData });
  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.type === 'number' ? Number(e.target.value) : e.target.value });
  const handleSubmit = (e) => { e.preventDefault(); onSubmit(form); };
  return (<form onSubmit={handleSubmit}><Input label="Full Name" name="name" value={form.name} onChange={handleChange} required /><Input label="Email" name="email" type="email" value={form.email} onChange={handleChange} required /><Input label="Phone" name="phone" value={form.phone} onChange={handleChange} required /><div className="grid grid-cols-2 gap-4"><div className="mb-4"><label className="block mb-1.5 text-sm font-medium" style={{ color: 'var(--color-text-primary)' }}>Role</label><select name="role" value={form.role} onChange={handleChange} className="w-full rounded-lg p-2.5 text-sm" style={{ backgroundColor: 'var(--color-surface-secondary)', border: '1px solid var(--color-border)', color: 'var(--color-text-primary)' }}>{MEMBER_ROLES.map(r => <option key={r} value={r}>{r.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}</option>)}</select></div><Input label="Department" name="department" value={form.department} onChange={handleChange} required /></div><div className="grid grid-cols-2 gap-4"><div className="mb-4"><label className="block mb-1.5 text-sm font-medium" style={{ color: 'var(--color-text-primary)' }}>Year</label><select name="year" value={form.year} onChange={handleChange} className="w-full rounded-lg p-2.5 text-sm" style={{ backgroundColor: 'var(--color-surface-secondary)', border: '1px solid var(--color-border)', color: 'var(--color-text-primary)' }}>{ACADEMIC_YEARS.map(y => <option key={y.value} value={y.value}>{y.label}</option>)}</select></div><Input label="Display Order" name="order" type="number" value={form.order} onChange={handleChange} /></div><Button type="submit" loading={loading} fullWidth className="mt-2">{initialData.name ? 'Update Member' : 'Add Member'}</Button></form>);
}
